### ISSUE TITLE
will the dataset be available?

### ISSUE THREAD

**Issue by huangk77** [Dr-zfeng/SPSNet#1]
Hello,

Congratulations，and thanks for your contribution.
I am interesting in your part segmentation of spacecraft, but there is no similar datasets as I kown.
Is the dataset will available on the schedule?

**Comment by Dr-zfeng** [comment]
> Hello,
> 
> Congratulations，and thanks for your contribution. I am interesting in your part segmentation of spacecraft, but there is no similar datasets as I kown. Is the dataset will available on the schedule?

Thank you for your interesting in our dataset. The dataset will released as soon as possible.

**Comment by huangk77** [comment]
Hi,
Glad to hear from you and congratulations on making your code open source. I'm confused that the open connection for the dataset is still the current page. Will you fix it?
Looking forward to your reply.

**Comment by Dr-zfeng** [comment]
> Hi, Glad to hear from you and congratulations on making your code open source. I'm confused that the open connection for the dataset is still the current page. Will you fix it? Looking forward to your reply.

The dataset will be released by Baidu DiskNet. However, the data set will be available a few days later because of the limited speed of upload.

**Comment by huangk77** [comment]
Thanks for your response, and best wishes.
